from datetime import datetime

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)

from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.units import inch


def create_pdf(
    pdf_path,
    filename,
    rows,
    cols,
    missing,
    duplicates,
    columns,
    insights
):

    doc = SimpleDocTemplate(pdf_path)

    styles = getSampleStyleSheet()

    title_style = styles["Heading1"]
    title_style.alignment = TA_CENTER
    title_style.textColor = colors.HexColor("#2A5298")

    heading_style = styles["Heading2"]
    heading_style.textColor = colors.HexColor("#2A5298")

    normal = styles["BodyText"]

    story = []

    # ----------------------------
    # Title
    # ----------------------------

    story.append(Paragraph("DataLens AI", title_style))
    story.append(Paragraph("Dataset Analysis Report", heading_style))
    story.append(Spacer(1, 0.3 * inch))

    # ----------------------------
    # Dataset Name
    # ----------------------------

    story.append(Paragraph(f"<b>Dataset:</b> {filename}", normal))
    story.append(Spacer(1, 0.2 * inch))

    # ----------------------------
    # Dataset Summary
    # ----------------------------

    story.append(Paragraph("<b>Dataset Summary</b>", heading_style))
    story.append(Spacer(1, 0.1 * inch))

    table_data = [
        ["Property", "Value"],
        ["Rows", rows],
        ["Columns", cols],
        ["Missing Values", missing],
        ["Duplicate Rows", duplicates]
    ]

    table = Table(table_data, colWidths=[220, 120])

    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2A5298")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 1, colors.grey),
        ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
    ]))

    story.append(table)
    story.append(Spacer(1, 0.3 * inch))

    # ----------------------------
    # Dataset Columns
    # ----------------------------

    story.append(Paragraph("<b>Dataset Columns</b>", heading_style))
    story.append(Spacer(1, 0.1 * inch))

    for column in columns:
        story.append(Paragraph(f"• {column}", normal))

    story.append(Spacer(1, 0.3 * inch))

    # ----------------------------
    # AI Insights
    # ----------------------------

    story.append(Paragraph("<b>AI Insights</b>", heading_style))
    story.append(Spacer(1, 0.1 * inch))

    for insight in insights:
        story.append(Paragraph(f"{insight}", normal))
        story.append(Spacer(1, 0.05 * inch))

    story.append(Spacer(1, 0.2 * inch))

    # ----------------------------
    # Date & Time
    # ----------------------------

    current_time = datetime.now().strftime("%d %B %Y, %I:%M:%S %p")

    story.append(
        Paragraph(
            f"<b>Report Generated On:</b> {current_time}",
            normal
        )
    )

    story.append(Spacer(1, 0.2 * inch))

    # ----------------------------
    # Footer
    # ----------------------------

    story.append(Paragraph("<b>Generated by DataLens AI</b>", normal))
    story.append(Paragraph("© 2026 DataLens AI", normal))

    doc.build(story)